// <auto-generated />
using System;
using System.Collections.Generic;
using Identity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241020164322_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Models.Permission", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Identity.Domain.Models.Permission.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Endpoint", "Identity.Domain.Models.Permission.Endpoint#ApiEndpoint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Method");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Path");
                        });

                    b.HasKey("Name");

                    b.ToTable("tblPermissions", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Models.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Identity.Domain.Models.Role.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");
                        });

                    b.HasKey("Name");

                    b.ToTable("tblRoles", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.ComplexProperty<Dictionary<string, object>>("Password", "Identity.Domain.Models.User.Password#Password", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Password");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblUsers", (string)null);
                });

            modelBuilder.Entity("tblRolePermissions", b =>
                {
                    b.Property<string>("PermissionsName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RolesName")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PermissionsName", "RolesName");

                    b.HasIndex("RolesName");

                    b.ToTable("tblRolePermissions");
                });

            modelBuilder.Entity("tblUserRoles", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesName", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("tblUserRoles");
                });

            modelBuilder.Entity("tblRolePermissions", b =>
                {
                    b.HasOne("Identity.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tblUserRoles", b =>
                {
                    b.HasOne("Identity.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
