// <auto-generated />
using System;
using System.Collections.Generic;
using Identity.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IdentityContext))]
    partial class IdentityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.API.Domain.Models.Permission", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Identity.API.Domain.Models.Permission.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Endpoint", "Identity.API.Domain.Models.Permission.Endpoint#ApiEndpoint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");
                        });

                    b.HasKey("Name");

                    b.ToTable("tblPermissions", (string)null);
                });

            modelBuilder.Entity("Identity.API.Domain.Models.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Identity.API.Domain.Models.Role.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");
                        });

                    b.HasKey("Name");

                    b.ToTable("tblRoles", (string)null);
                });

            modelBuilder.Entity("Identity.API.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblUsers", (string)null);
                });

            modelBuilder.Entity("tblRolePermissions", b =>
                {
                    b.Property<string>("PermissionsName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RolesName")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PermissionsName", "RolesName");

                    b.HasIndex("RolesName");

                    b.ToTable("tblRolePermissions");
                });

            modelBuilder.Entity("tblUserRoles", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesName", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("tblUserRoles");
                });

            modelBuilder.Entity("tblRolePermissions", b =>
                {
                    b.HasOne("Identity.API.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.API.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tblUserRoles", b =>
                {
                    b.HasOne("Identity.API.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.API.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
